import type { Metadata } from "next";
import { healthPrivacyPublished } from "@/lib/healthPrivacyRelease";

// Consumer Health Data Privacy Policy — public surface.
//
// LEGAL COPY: render verbatim. This text is the counsel-approved policy and
// must stay identical to the app repo source of truth
// (lib/custom_code/copy/consumer_health_data_privacy_copy.dart, commit daa376a).
// Same policy, two surfaces — do not let them drift. Guarded by
// scripts/verify-health-privacy.mjs (npm run test:policy).
//
// While the release gate is off, keep the page out of search indexes. The gate
// (HEALTH_PRIVACY_PUBLISHED) is the single switch for indexing; this only reads
// it, it does not flip it.
export const metadata: Metadata = {
  title: "Consumer Health Data Privacy Policy — SoulAnthem",
  description:
    "How SoulAnthem and Pyrigen Incorporated handle consumer health data under applicable state health privacy laws.",
  robots: healthPrivacyPublished ? undefined : { index: false, follow: false },
};

export default function HealthPrivacy() {
  return (
    <main className="mx-auto max-w-3xl px-6 pt-32 pb-24">
      <h1 className="text-4xl font-semibold tracking-tight">
        Consumer Health Data Privacy Policy
      </h1>
      <p className="mt-3 text-sm text-black/40">Effective Date: [Insert Date, 2026]</p>

      <p className="mt-8 text-lg leading-relaxed text-black/60">
        This Consumer Health Data Privacy Policy supplements our General Privacy Policy and applies
        specifically to &quot;consumer health data&quot; as defined by applicable state health privacy laws.
      </p>

      <h2 className="mt-12 text-xl font-semibold tracking-tight">
        1. Categories of Consumer Health Data We Collect
      </h2>
      <p className="mt-4 text-black/60">
        Through your use of SoulAnthem, we may collect information linked or reasonably linkable to your
        physical or mental health status, including:
      </p>
      <p className="mt-4 text-black/60">
        {
          "Goals, feelings, and check-in inputs. We may collect the goals you select or write, including preset goal selections and custom goal text, the feelings or voice-style preferences you select, and any check-in inputs you provide."
        }
      </p>
      <p className="mt-4 text-black/60">
        {
          "Optional free-text entries. We may collect words you enter to personalize your experience, such as goal descriptions, mental-block text, or other reflections you choose to provide."
        }
      </p>
      <p className="mt-4 text-black/60">
        {
          "Generated content and saved activity. We may collect and store affirmations, anthem scripts, generated audio references, ratings, rituals, journeys, and other content or activity created through your use of SoulAnthem."
        }
      </p>
      <ul className="mt-4 space-y-3 text-black/60">
        <li>
          <span className="font-medium text-black/80">Safety Inferences:</span> Data generated by our
          internal safety systems that detect potential self-directed negativity or self-harm signals
          within your text entries to provide crisis resources.
        </li>
      </ul>

      <h2 className="mt-12 text-xl font-semibold tracking-tight">2. Sources of Consumer Health Data</h2>
      <p className="mt-4 text-black/60">
        We collect Consumer Health Data directly from you through your choices, entries, and activity in
        SoulAnthem, and generate certain content and safety inferences through operation of the service.
      </p>

      <h2 className="mt-12 text-xl font-semibold tracking-tight">
        3. Why We Collect and Use Consumer Health Data
      </h2>
      <p className="mt-4 text-black/60">
        We process your consumer health data based strictly on your affirmative opt-in consent for the
        following purposes:
      </p>
      <p className="mt-4 text-black/60">
        {
          "We require Consumer Health Data consent before generation because SoulAnthem's generation experience uses the goals, feelings, check-in inputs, free-text entries, and generated content associated with your account."
        }
      </p>
      <p className="mt-4 text-black/60">
        {
          "We use this information to generate affirmations, anthem scripts and audio, personalize your SoulAnthem experience, support safety and distress handling, save content you choose to keep, operate and secure the service, respond to privacy and support requests, and provide the features described in this Consumer Health Data Privacy Policy."
        }
      </p>

      <h2 className="mt-12 text-xl font-semibold tracking-tight">
        4. How We Process and Disclose Consumer Health Data
      </h2>
      <p className="mt-4 text-black/60">
        We do not sell your consumer health data, nor do we share it with third parties for their own
        independent commercial or marketing purposes.
      </p>
      <p className="mt-4 text-black/60">
        We use carefully selected service providers that assist us in delivering SoulAnthem&apos;s
        functionality, including AI text generation, safety analysis, hosting, storage, and audio
        generation services. Where user content is processed by these providers, we require contractual
        and technical safeguards designed to protect the confidentiality and security of the information.
      </p>
      <p className="mt-4 text-black/60">
        Before transmitting user-generated content to certain service providers, we remove or minimize
        direct identifying information where reasonably possible. Depending on the service being used,
        these providers may receive user-generated content without associated account identifiers such as
        email addresses, user IDs, device identifiers, IP addresses, or similar direct identifying
        information. This safeguard is designed to reduce the extent to which information processed by
        those providers can be associated with a particular user. Some service providers, such as our
        hosting, authentication, database, security, payment, or account-management providers, may process
        information that remains associated with a user where necessary to operate SoulAnthem, maintain
        user accounts, process subscriptions, provide security, comply with legal obligations, or deliver
        requested services.
      </p>
      <p className="mt-4 text-black/60">
        When Consumer Health Data or similar wellness-related content is processed by a service provider on
        our behalf, the provider is authorized to use the information only for the purpose of providing
        services to SoulAnthem, maintaining the security and integrity of its systems, satisfying legal
        obligations, or as otherwise permitted by applicable law and contractual commitments.
      </p>
      <p className="mt-4 text-black/60">
        We use limited analytics and performance-monitoring tools to understand product usage, reliability,
        and performance. We do not send emotional free-text entries, mental-block text, affirmation text,
        anthem script text, goal names, believability ratings, account email addresses, or Consumer Health
        Data content to analytics. Analytics events are limited to pseudonymous product usage and
        performance information, including standard app, device, session, page/route, and non-user-authored
        route identifier information, and are not used for advertising targeting.
      </p>

      <h2 className="mt-12 text-xl font-semibold tracking-tight">
        5. Your Rights Regarding Consumer Health Data
      </h2>
      <p className="mt-4 text-black/60">
        You have the right to confirm whether we collect your consumer health data and access a copy of
        it, withdraw your consent to our future collection and processing of your data at any time, and
        request the deletion of your consumer health data as described below.
      </p>
      <p className="mt-4 text-black/60">
        You may exercise these rights by contacting us at privacy@pyrigen.com or through the in-app privacy
        menu. If you contact support@pyrigen.com with a privacy or data-rights request, we will route your
        request to our privacy process. We will authenticate your request before acting on it. If we deny a
        request, you will be provided with written justification and instructions on how to appeal our
        decision.
      </p>
      <p className="mt-4 text-black/60">
        Our response timeframes, deletion process, backup-system treatment, and service-provider retention
        limitations are described in Section 6.
      </p>

      <h2 className="mt-12 text-xl font-semibold tracking-tight">
        6. Retention, Deletion, and Protection of Consumer Health Data
      </h2>
      <p className="mt-4 text-black/60">
        We retain Consumer Health Data only for as long as reasonably necessary to provide SoulAnthem,
        maintain user accounts and saved content, comply with legal obligations, resolve disputes, enforce
        agreements, protect the security and integrity of our platform, and support the purposes described
        in this Consumer Health Data Privacy Policy.
      </p>
      <p className="mt-4 text-black/60">
        When you submit a verified request to access, confirm, withdraw consent for, or delete Consumer
        Health Data, we will respond without undue delay and within the timeframes required by applicable
        law. For Washington Consumer Health Data requests, we generally respond within 45 days of receiving
        the request. Where permitted by law and reasonably necessary due to the complexity or number of
        requests, we may extend that period once by an additional 45 days and will notify you of the
        extension and the reason for it.
      </p>
      <p className="mt-4 text-black/60">
        When we verify a deletion request, we will delete or de-identify applicable Consumer Health Data
        from our active systems in accordance with applicable law, except where retention is legally
        required or otherwise permitted. Information stored in archived, backup, disaster-recovery,
        security, or similar systems may take longer to remove. Where Washington&apos;s My Health My Data
        Act applies, deletion from archived or backup systems will not be delayed longer than permitted by
        that law.
      </p>
      <p className="mt-4 text-black/60">
        Certain authorized service providers that process data on our behalf may retain limited categories
        of information for backup, security, fraud prevention, auditing, disaster recovery, legal
        compliance, or similar operational purposes where permitted by applicable law and contractual
        commitments. Where such retention occurs, those providers remain subject to contractual,
        administrative, technical, and organizational safeguards designed to protect the information,
        restrict its use, and preserve its confidentiality. Our audio-generation provider may retain
        non-account-linked generated script text under its applicable terms and data controls; this
        provider does not receive raw user free-text or account identifiers from SoulAnthem.
      </p>
      <p className="mt-4 text-black/60">
        We do not promise immediate deletion from every processor environment in all circumstances.
        Instead, we delete or de-identify Consumer Health Data from our systems as required by law and
        require our service providers to protect retained information and delete, dispose of, or limit
        further use of that information in accordance with their contractual obligations and applicable
        legal requirements.
      </p>

      <h2 className="mt-12 text-xl font-semibold tracking-tight">7. De-identification Commitment</h2>
      <p className="mt-4 text-black/60">
        Pyrigen Incorporated commits to maintaining de-identified data in its anonymous form and will not
        attempt to re-identify it.
      </p>

      <p className="mt-16">
        <a href="/" className="text-[var(--accent)] hover:underline">
          &larr; Back to SoulAnthem
        </a>
      </p>
    </main>
  );
}
